// SPDX-License-Identifier: GPL-3.0-only
#include <QGuiApplication>
#include <QFile>
#include <QDir>
#include <QJsonDocument>
#include <QJsonArray>
#include <QImage>
#include <QTextLayout>
#include <QGlyphRun>
#include <QPainterPath>
#include <QTextStream>

static QString number(qreal value) { return QString::number(value, 'f', 4); }
static QString key(const QString &text) {
    QStringList codes;
    for (auto code : text.toUcs4()) codes << QString::number(code, 16);
    return codes.join('-');
}
static QString svgPath(const QPainterPath &path) {
    QString result;
    for (int i = 0; i < path.elementCount(); ++i) {
        auto e = path.elementAt(i);
        if (e.isMoveTo()) result += "M" + number(e.x) + " " + number(e.y);
        else if (e.isLineTo()) result += "L" + number(e.x) + " " + number(e.y);
        else if (e.type == QPainterPath::CurveToElement) {
            auto b = path.elementAt(++i), c = path.elementAt(++i);
            result += "C" + number(e.x) + " " + number(e.y) + " " + number(b.x) + " " + number(b.y) + " " + number(c.x) + " " + number(c.y);
        }
    }
    return result;
}
int main(int argc, char **argv) {
    QGuiApplication app(argc, argv);
    auto args = app.arguments();
    if (args.size() != 4) return 2;
    if (args[1] == "--render") return QImage(args[2]).save(args[3]) ? 0 : 4;
    if (args[1] == "--rgba") {
        auto image = QImage(args[2]).convertToFormat(QImage::Format_RGBA8888);
        if (image.isNull()) return 3;
        QFile output(args[3]); if (!output.open(QIODevice::WriteOnly)) return 4;
        for (int y = 0; y < image.height(); ++y) output.write(reinterpret_cast<const char *>(image.constScanLine(y)), image.width() * 4);
        QFile meta(args[3] + ".json"); if (!meta.open(QIODevice::WriteOnly)) return 4;
        meta.write(QJsonDocument(QJsonArray{image.width(), image.height()}).toJson());
        return 0;
    }
    QFile specification(args[1]); if (!specification.open(QIODevice::ReadOnly)) return 3;
    auto texts = QJsonDocument::fromJson(specification.readAll()).array();
    QDir directory(args[2]); directory.mkpath("glyphs");
    QStringList keys;
    for (const auto &value : texts) {
        auto text = value.toString();
        QFont font(args[3]); font.setPixelSize(256); font.setHintingPreference(QFont::PreferNoHinting);
        QTextLayout layout(text, font);
        layout.beginLayout(); auto line = layout.createLine(); line.setLineWidth(10000); layout.endLayout();
        QPainterPath outline;
        QStringList families;
        for (const auto &run : layout.glyphRuns()) {
            auto glyphs = run.glyphIndexes(); auto positions = run.positions();
            for (int i = 0; i < glyphs.size(); ++i) outline.addPath(run.rawFont().pathForGlyph(glyphs[i]).translated(positions[i]));
            families << run.rawFont().familyName();
        }
        if (outline.isEmpty()) return 5;
        auto box = outline.boundingRect(); auto name = key(text); keys << name;
        QFile output(directory.filePath("glyphs/" + name + ".svg")); if (!output.open(QIODevice::WriteOnly)) return 4;
        auto svg = QString("<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"%1 %2 %3 %4\"><title>%5</title><desc>Vector outlines from %6; GPL-3.0-only artwork.</desc><path fill=\"#fff\" fill-rule=\"evenodd\" d=\"%7\"/></svg>\n")
            .arg(number(box.x()), number(box.y()), number(box.width()), number(box.height()), text.toHtmlEscaped(), families.join(", ").toHtmlEscaped(), svgPath(outline));
        output.write(svg.toUtf8());
    }
    QFile index(directory.filePath("Glyphs.js")); if (!index.open(QIODevice::WriteOnly)) return 4;
    QJsonArray array; for (const auto &name : keys) array.append(name);
    index.write("// Generated by tools/export-icons.cpp; SPDX-License-Identifier: GPL-3.0-only\nvar available = " + QJsonDocument(array).toJson(QJsonDocument::Compact) + ";\n");
    index.write("function fileFor(text) { text = String(text); var codes = []; for (var i = 0; i < text.length; i++) { var code = text.charCodeAt(i); if (code >= 0xd800 && code <= 0xdbff && i + 1 < text.length) { var low = text.charCodeAt(i + 1); if (low >= 0xdc00 && low <= 0xdfff) { code = 0x10000 + (code - 0xd800) * 0x400 + low - 0xdc00; i++; } } codes.push(code.toString(16)); } var key = codes.join('-'); return available.indexOf(key) < 0 ? '' : 'glyphs/' + key + '.svg'; }\n");
    index.write("if (typeof module !== 'undefined') module.exports = {available: available, fileFor: fileFor};\n");
    return 0;
}
